cms/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.inicio, name='inicio' ),
    url(r'^resultados/$', views.busqueda, name='busqueda'),
    url(r'^login/$', views.entrar, name='login'),
    url(r'^terminos/', views.terminos, name='terminos'),
    url(r'^reproductor/(?P<pk>[0-9]+)/$', views.reproductor, name='reproductor'),
    url(r'^perfil/(?P<pk>[0-9]+)/$', views.perfil, name='perfil'),
    url(r'^logout/$', auth_views.logout, {'next_page' : '/'}, name='logout'),
    url(r'^registro/$', views.registro, name='registro'),
    url(r'^actualizar/$', views.actualizar_perfil, name='actualizar'),
    url(r'sugerencias/$',views.sugerencias, name='sugerencias'),
    url(r'categorias/$', views.categorias, name='categoria'),
    url(r'agr_fav/$', views.agr_fav, name='agr_fav'),
    url(r'agr_val/$', views.agr_valoracion, name='agr_val'),
    url(r'categoria/$', views.categoriam, name='cate'),
]

zinemas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
handler404 = 'cms.views.error404'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('cms.urls', namespace='cms')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/categoria.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Zinemas</title>
        <link rel="icon" sizes="192x192" href="{% static 'imagenes/web/favicon.png' %}">
        <script src='{% static 'js/jquery.js' %}'></script>
        <link rel="stylesheet" href="{% static 'css/inicio.css' %}" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="{% static 'js/general.js' %}"></script>
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head>
    <body>
      {% if tipo == 'video' %}
      <div class='pelicula_box_cont' >
      {% for x in contenido %}
      <!-- CAJA -->
      <div class='caj'>
        <div class='caja' style='background:url({{ x.poster.url }}) center no-repeat; background-size:cover;' onclick="sinopsis({{ x.pk }}, 'abrir', '{{ x.trailer }}')">
            <div class='caja_repre'>
                <i>play_circle_filled</i>
            </div>
            <div class='calidad'>
              {{ x.calidad }}
            </div>
            <div class='valoracion'>
              {{ x.valoracion }} <i>grade</i>
            </div>
        </div>
        <div class='caja_info'>
          {{ x.titulo }}
          <br>
          <p>{{ x.fecha|slice:"11" }}</p>
        </div>
      </div>
      <!-- SINOPSIS DE LA CAJA -->
      <div class='pelicula_repre' id='pelicula_repre{{x.pk}}'>
              <div class='pelicula_repre_cont'>
                  <div class='sinopsis_left'>
                      <div class='sinopsis_repre' style="background:url({{ x.poster.url }}) center no-repeat; background-size:cover;">
                      </div>
                      <a href="{% url 'cms:reproductor' pk=x.pk %}">
                        <div class='agr_pelicula'>
                            Ver pelicula
                        </div>
                      </a>
                      {% if user.is_authenticated %}
                          <div class='agr_favorito' onclick="agr_fav({{ x.pk }})">
                              Agregar a favoritos
                          </div>
                      {% endif %}
                      <a href='{{ x.descarga }}' target="_blank">
                        <div class='agr_descargar'>
                            Descargar pelicula
                        </div>
                      </a>
                  </div>
                  <div class='sinopsis_right'>
                      <h2>{{x.titulo}}</h2>
                      <p>{{ x.sinopsis }}</p>
                      <div id='iframe_yt{{ x.pk }}'></div>
                  </div>
                  <div class='sinopsis_close' onclick="sinopsis({{x.pk}}, 'cerrar')">
                      <i>close</i>
                  </div>
              </div>
          </div>
      {% endfor %}
    </div>
    {% if contenido.has_previous or contenido.has_next %}
    <h3 style="text-align:center;">Pagina {{ contenido.number }} de {{ contenido.paginator.num_pages }}</h3>
    {% endif %}
    <div class='control_categoria'>
      {% if contenido.has_previous %}
        <h4>Anterior pagina | </h4> <div class='next' onclick="ajax_categoria('{{categoria}}',{{ contenido.previous_page_number }})"><i>keyboard_arrow_left</i></div>
      {% endif %}
      {% if contenido.has_next %}
        <h4>Siguiente pagina | </h4>  <div class='next' onclick="ajax_categoria('{{categoria}}',{{ contenido.next_page_number }})"><i>keyboard_arrow_right</i></div>
      {% endif %}
    </div>
      {% else %}
      <div class='pelicula_box_cont' >
      {% for x in contenido %}
      <!-- CAJA -->
      <div class='caj'>
        <div class='caja' style='background:url({{ x.videopk.poster.url }}) center no-repeat; background-size:cover;' onclick="sinopsis({{ x.videopk.pk }}, 'abrir', '{{ x.videopk.trailer }}')">
            <div class='caja_repre'>
                <i>play_circle_filled</i>
            </div>
            <div class='calidad'>
              {{ x.videopk.calidad }}
            </div>
            <div class='valoracion'>
              {{ x.videopk.valoracion }} <i>grade</i>
            </div>
        </div>
        <div class='caja_info'>
          {{ x.videopk.titulo }}
          <br>
          <p>{{ x.videopk.fecha|slice:"11" }}</p>
        </div>
      </div>
      <!-- SINOPSIS DE LA CAJA -->
      <div class='pelicula_repre' id='pelicula_repre{{x.videopk.pk}}'>
              <div class='pelicula_repre_cont'>
                <div class='sinopsis_left'>
                    <div class='sinopsis_repre' style="background:url({{ x.videopk.poster.url }}) center no-repeat; background-size:cover;">
                    </div>
                    <a href="{% url 'cms:reproductor' pk=x.videopk.pk %}">
                      <div class='agr_pelicula'>
                          Ver pelicula
                      </div>
                    </a>
                    {% if user.is_authenticated %}
                        <div class='agr_favorito' onclick="agr_fav({{ x.videopk.pk }})">
                            Agregar a favoritos
                        </div>
                    {% endif %}
                    <a href='{{ x.videopk.descarga }}' target="_blank">
                      <div class='agr_descargar'>
                          Descargar pelicula
                      </div>
                    </a>
                </div>
                  <div class='sinopsis_right'>
                      <h2>{{x.videopk.titulo}}</h2>
                      <p>{{ x.videopk.sinopsis }}</p>
                      <div id='iframe_yt{{ x.videopk.pk }}'></div>
                  </div>
                  <div class='sinopsis_close' onclick="sinopsis({{x.videopk.pk}}, 'cerrar')">
                      <i>close</i>
                  </div>
              </div>
          </div>
      {% endfor %}
    </div>
    {% if contenido.has_previous or contenido.has_next %}
    <h3 style="text-align:center;">Pagina {{ contenido.number }} de {{ contenido.paginator.num_pages }}</h3>
    {% endif %}

      <div class='control_categoria'>
      {% if contenido.has_previous %}
      <h4>Anterior pagina | </h4> <div class='next' onclick="ajax_categoria('{{categoria}}',{{ contenido.previous_page_number }})"><i>keyboard_arrow_left</i></div>
    {% endif %}
    {% if contenido.has_next %}
      <h4>Siguiente pagina | </h4>  <div class='next' onclick="ajax_categoria('{{categoria}}',{{ contenido.next_page_number }})"><i>keyboard_arrow_right</i></div>
      {% endif %}
    </div>
      {% endif %}

</body>
</html>

templates/error404.html
{% extends 'header&footer.html' %}
{% block contenido %}

                   <div class='error_404'>
                        <h2>ERROR 404</h2>
                       <h3>Contenido no disponible</h3>
                    </div>

{% endblock %}

templates/header&footer.html
<!--HEADER-->
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Zinemas</title>
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <link rel="icon" sizes="192x192" href="{% static 'imagenes/web/favicon.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/inicio.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/general.js' %}"></script>
        <link href='https://fonts.googleapis.com/css?family=Carter+One' rel='stylesheet' type='text/css'>
        <script type="text/javascript">
        function ajax_categoria(tipo, pag){
          var conexion;
          conexion = new XMLHttpRequest();
          conexion.onreadystatechange =  function(){
            if(conexion.readyState == 4 && conexion.status == 200){
              document.getElementById("categoria_"+tipo).innerHTML = conexion.responseText;
            }
          }
          conexion.open("GET","{% url 'cms:categoria' %}?categoria="+tipo+"&pag="+pag,true);
          conexion.send();
        }

        function resultados(str){
          if(str.length==0){
              $('.resultados').css({"height":0});
          }else{
              $('.resultados').css({"height":'auto'});
          }
          var conexion;
          if(str.length==0){
            document.getElementById("resultados").innerHTML=" ";
          }
          conexion = new XMLHttpRequest();
          conexion.onreadystatechange =  function(){
            if(conexion.readyState==4 && conexion.status==200){
              document.getElementById("resultados").innerHTML=conexion.responseText;
            }
          }
          conexion.open("GET","{% url 'cms:sugerencias' %}?sug="+str,true);
          conexion.send();
        }

        function agr_fav(pk){
          alert("Pelicula agregada a favoritos");
          var conexion;
          conexion = new XMLHttpRequest();
          conexion.onreadystatechange =  function(){
            if(conexion.readyState==4 && conexion.status==200){
              document.getElementById("ok").innerHTML=conexion.responseText;
            }
          }
          conexion.open("GET","{% url 'cms:agr_fav' %}?pk="+pk,true);
          conexion.send();
        }
        function agr_val(pk){
          alert("Pelicula agregada a valoradas");
          var conexion;
          conexion = new XMLHttpRequest();
          conexion.onreadystatechange =  function(){
            if(conexion.readyState==4 && conexion.status==200){
              document.getElementById("ok").innerHTML=conexion.responseText;
            }
          }
          conexion.open("GET","{% url 'cms:agr_val' %}?pk="+pk,true);
          conexion.send();
        }
        </script>
    </head>
    <body>
        <div class='cont'>
            <header>
                <nav>
                    <div class='logo' onclick="window.location='{% url 'cms:inicio' %}';">
                        <img src="{% static 'imagenes/web/logo.png' %}">
                    </div>
                    <div class='buscador'>
                      <form method="GET" action="{% url 'cms:busqueda' %}" autocomplete="off">
                        <div class="etc"><input type="text"  name='clave' placeholder="¿Qué deseas buscar?" onkeyup="resultados(this.value)"><button type="submit"><i>search</i></button></div>
                        <div class='resultados' id='resultados'>
                        </div>
                      </form>
                    </div>

                    {% if user.is_authenticated %}
                      <div class='sesion'>
                          <i>person</i>
                          <h3>{{ user.username }} </h3>
                          <div class='sesion_cont'>
                              <a href='{% url 'cms:perfil' pk=user.pk %}'><p><i>contacts</i> Mi pefil</p></a>
                              <a href='{% url 'cms:logout' %}'><p><i>cancel</i>Cerrar sesion</p></a>
                          </div>
                      </div>
                    {% else %}
                      <div class='iniciar' onclick="window.location='{% url 'cms:login' %}';">Iniciar sesion</div>
                    {% endif %}
                </nav>
            </header>
    <!--/HEADER-->
            <div class='contenedor'>
                <div class='general_box'>
                  {% block contenido %}{% endblock contenido %}
                </div>
            </div>
    <!--FOOTER-->
    </div>
    <footer>
      <div class='footer_top'>
        <div class='footer_box'>
              <h2>Urls</h2>
              <a href='{% url 'cms:terminos' %}'>Términos y condiciones</a>
              <a href='http://www.fegarza.com' target="_blank">Página web del desarrollador</a>
          </div>
          <div class='footer_box'>
              <h2>Nuestras redes sociales</h2>
              <p>Mantente informado de lo que pasa en Zinemas</p>
              <div class='social_footer'>
                  <a href="https://www.facebook.com/Zinemas-533033066871384/?ref=ts&fref=ts" target="_blank"><img src='{% static 'imagenes/social/facebook.png' %}' width="35px"></a>
                  <a href="#"><img src='{% static 'imagenes/social/twitter.png' %}' width="35px"></a>
              </div>
          </div>
          <div class='footer_box'>
              <h2>Sobre nosostros</h2>
              <p>Pagina web desarrollada por Juan Felipe Garza Sánchez</p>
              <a href="https://www.facebook.com/index6" target="_blank">
                <div class='contactanos'>
                    CONTACTANOS
                </div>
              </a>
          </div>
        </div>
        <div class='footer_bottom'>
          Zinemas 2016 | © Todos los derechos reservados
        </div>
    </footer>
  </body>
</html>
<!--/FOOTER-->

templates/inicio.html
{% extends 'header&footer.html' %}

{% block contenido %}
                    <div class='repre'>
                        <div class='repre_cont'>
 
                          {% for x in slider %}
                            <div class='slider' style="background:url({{ x.fondo.url }}) top no-repeat; background-size:cover; ">
                                <a href='{% url 'cms:reproductor' pk=x.videopk.pk %}'><div class='ver_pelicula'>Mirar pelicula</div></a>
                            </div>
                          {% endfor %}
 
                        </div>
                        <div class='repre_right'><i>keyboard_arrow_right</i></div>
                        <div class='repre_left'><i>keyboard_arrow_left</i></div>
                    </div>
                    <div class='categorias'>
                        <div class='ver_categorias'>
                            Ver categorias <i>arrow_downward</i>
                        </div>
                        <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=accion';">
                            <i>whatshot</i>
                            <p>Acción</p>
                        </div>
                        <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=romance';">
                            <i>favorite</i>
                            <p>Romance</p>
                        </div>
                        <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=infantil';">
                            <i>face</i>
                            <p>Infantiles</p>
                        </div>
                        <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=terror';">
                            <i>mood_bad</i>
                            <p>Terror</p>
                        </div>
                        <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=anime';">
                            <i>adb</i>
                            <p>Anime</p>
                        </div>
                         <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=documental';">
                            <i>public</i>
                            <p>Documental</p>
                        </div>
                        <div class='categoria' onclick="window.location='{% url 'cms:cate' %}?categoria=drama';">
                            <i>star</i>
                            <p>Drama</p>
                        </div>
                        <div class='categoria'onclick="window.location='{% url 'cms:cate' %}?categoria=comedia';">
                            <i>sentiment_very_satisfied</i>
                            <p>Comedia</p>
                        </div>
                    </div>
                    <div class='pelicula_box'>
                        <h1 style='background:#4CAF50;'>Ultimas peliculas subidas</h1>
                        <div class='pelicula_box_cont_opc' id='categoria_todos'>
                          <script type="text/javascript">
                            ajax_categoria("todos",1);
                          </script>
                        </div>
                    </div>
                    <div class='pelicula_box'>
                        <h1 style='background:#3F51B5;'>Estrenos</h1>
                        <div class='pelicula_box_cont_opc' id='categoria_estreno'>
                          <script type="text/javascript">
                            ajax_categoria("estreno",1);
                          </script>
                        </div>
                    </div>
                    <div class='pelicula_box'>
                        <h1 style='background:#E91E63;'>Peliculas mas vistas</h1>
                        <div class='pelicula_box_cont_opc' id='categoria_vistas'>
                          <script type="text/javascript">
                            ajax_categoria("vistas",1);
                          </script>
                        </div>
                    </div>
                    <div class='pelicula_box'>
                        <h1 style='background:#F44336;'>Peliculas mejor valoradas</h1>
                        <div class='pelicula_box_cont_opc' id='categoria_valoracion'>
                          <script type="text/javascript">
                            ajax_categoria("valoracion",1);
                          </script>
                        </div>
                    </div>
                    <div class='pelicula_box'>
                        <h1 style='background:#009688;'>Peliculas recomendadas</h1>
                        <div class='pelicula_box_cont_opc' id='categoria_favoritos'>
                          <script type="text/javascript">
                            ajax_categoria("favoritos",1);
                          </script>
                        </div>
                    </div>
{% endblock %}

templates/login.html
{% extends "header&footer.html" %}
 {% block contenido %}
<div class="login">
  {% load staticfiles %}
    <div class="login_cont">
        <img src='{% static 'imagenes/web/favicon.png' %}'>
        <h3>Bienvenido a Zinemas</h3>
        <div class='form'>
            <form method="POST">
              {% csrf_token %}
                <input type="text" placeholder="Usuario" name="us">
                <input type="password" placeholder="Contraseña" name="pw">
                <button type="submit">ENTRAR</button>
                <a href="{% url 'social:begin' 'facebook' %}"><div class='login_facebook'>INICIAR SESION CON FACEBOOK</div></a>
            </form>
        </div>
    </div>
</div>
  <div class='registrarme'>
        <p>¿No tienes cuenta?</p>  <a href="{% url 'cms:registro' %}">Resgistrate aqui</a>
</div>
{% endblock contenido %}

templates/perfil.html
{% extends 'header&footer.html' %}
{% block contenido %}
{% load staticfiles %}

                  <div class='perfil_repre' style="background:url({% static 'imagenes/web/fondo.png' %}) center no-repeat; background-size:cover;">
                        <div class='perfil_img' style="background:url({% if tipo == 'facebook' %}https://graph.facebook.com/{{ contenido.uid }}/picture?type=large&return_ssl_resources=1{% else %}{{ contenido.perfil.url }}{% endif %}) center no-repeat; background-size:cover;">

                        </div>
                        <h2>{% if tipo == 'facebook' %}{{ contenido.user.username }}{% else %}{{ contenido.user_id.username }}{% endif %}</h2>
                    </div>
                    <div class='favoritos'>
                        <h1>Peliculas favoritas</h1>
                        <div class="pelicula_box_cont_opc">
                        <div class='pelicula_box_cont'>
                          {% for x in favoritos %}
                          <!-- CAJA -->
                          <div class='caj'>
                            <div class='caja' style='background:url({{ x.video.poster.url }}) center no-repeat; background-size:cover;' onclick="sinopsis({{ x.video.pk }}, 'abrir', '{{ x.video.trailer }}')">
                                <div class='caja_repre'>
                                    <i>play_circle_filled</i>
                                </div>
                                <div class='calidad'>
                                  {{ x.video.calidad }}
                                </div>
                                <div class='valoracion'>
                                  {{ x.video.valoracion }} <i>grade</i>
                                </div>
                            </div>
                            <div class='caja_info'>
                              {{ x.video.titulo }}
                              <br>
                              <p>{{ x.video.fecha|slice:"11" }}</p>
                            </div>
                          </div>
                          <!-- SINOPSIS DE LA CAJA -->
                          <div class='pelicula_repre' id='pelicula_repre{{x.video.pk}}'>
                                  <div class='pelicula_repre_cont'>
                                    <div class='sinopsis_left'>
                                        <div class='sinopsis_repre' style="background:url({{ x.video.poster.url }}) center no-repeat; background-size:cover;">
                                        </div>
                                        <a href="{% url 'cms:reproductor' pk=x.video.pk %}">
                                          <div class='agr_pelicula'>
                                              Ver pelicula
                                          </div>
                                        </a>
                                        {% if user.is_authenticated %}
                                            <div class='agr_favorito' onclick="agr_fav({{ x.video.pk }})">
                                                Agregar a favoritos
                                            </div>
                                        {% endif %}
                                        <a href='{{ x.video.descarga }}' target="_blank">
                                          <div class='agr_descargar'>
                                              Descargar pelicula
                                          </div>
                                        </a>
                                    </div>
                                      <div class='sinopsis_right'>
                                          <h2>{{x.video.titulo}}</h2>
                                          <p>{{ x.video.sinopsis }}</p>
                                          <div id='iframe_yt{{ x.video.pk }}'></div>
                                      </div>
                                      <div class='sinopsis_close' onclick="sinopsis({{x.video.pk}}, 'cerrar')">
                                          <i>close</i>
                                      </div>
                                  </div>
                              </div>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                     <div class='valoraciones'>
                        <h1>Peliculas valoradas</h1>
                        <div class="pelicula_box_cont_opc">
                        <div class='pelicula_box_cont'>
                          {% for x in valoraciones %}
                          <!-- CAJA -->
                          <div class='caj'>
                            <div class='caja' style='background:url({{ x.video.poster.url }}) center no-repeat; background-size:cover;' onclick="sinopsis({{ x.video.pk }}, 'abrir', '{{ x.video.trailer }}')">
                                <div class='caja_repre'>
                                    <i>play_circle_filled</i>
                                </div>
                                <div class='calidad'>
                                  {{ x.video.calidad }}
                                </div>
                                <div class='valoracion'>
                                  {{ x.video.valoracion }} <i>grade</i>
                                </div>
                            </div>
                            <div class='caja_info'>
                              {{ x.video.titulo }}
                              <br>
                              <p>{{ x.video.fecha|slice:"11" }}</p>
                            </div>
                          </div>
                          <!-- SINOPSIS DE LA CAJA -->
                          <div class='pelicula_repre' id='pelicula_repre{{x.video.pk}}'>
                                  <div class='pelicula_repre_cont'>
                                    <div class='sinopsis_left'>
                                        <div class='sinopsis_repre' style="background:url({{ x.video.poster.url }}) center no-repeat; background-size:cover;">
                                        </div>
                                        <a href="{% url 'cms:reproductor' pk=x.video.pk %}">
                                          <div class='agr_pelicula'>
                                              Ver pelicula
                                          </div>
                                        </a>
                                        {% if user.is_authenticated %}
                                            <div class='agr_favorito' onclick="agr_fav({{ x.video.pk }})">
                                                Agregar a favoritos
                                            </div>
                                        {% endif %}
                                        <a href='{{ x.video.descarga }}' target="_blank">
                                          <div class='agr_descargar'>
                                              Descargar pelicula
                                          </div>
                                        </a>
                                    </div>
                                      <div class='sinopsis_right'>
                                          <h2>{{x.video.titulo}}</h2>
                                          <p>{{ x.video.sinopsis }}</p>
                                          <div id='iframe_yt{{ x.video.pk }}'></div>
                                      </div>
                                      <div class='sinopsis_close' onclick="sinopsis({{x.video.pk}}, 'cerrar')">
                                          <i>close</i>
                                      </div>
                                  </div>
                              </div>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
{% endblock %}

templates/registro.html
{% extends 'header&footer.html' %}
{% block contenido %}
{% load staticfiles %}
          {% if contenido != "ninguno" %}
          <div class="errores">
              {{ contenido }}
          </div>
          {% endif %}
            <div class='registro'>
                        <div class='registro_left'>
                            <div class="registro_logo">
                            <img src="{% static 'imagenes/web/logo.png' %}">
                            </div>
                            <div class='registro_box'>
                                <h2>Mejor experiencia</h2>
                                <p>
                                    Podras tener la posibilidad de agregar paliculas favoritas y valoradas a tu perfil
                                </p>
                            </div>
                            <div class='registro_box'>
                                <h2>Social</h2>
                                <p>
                                    Podras compartir y disfrutar las peliculas conn tus amigos totalmente gratis
                                </p>
                            </div>
                            <div class='registro_box'>
                                <h2>Empieza ahora</h2>
                                <p>
                                  Acceso ilimitado a todas las peliculas de Zinemas
                                </p>
                            </div>
                        </div>
                        <div class='registro_right'>
                       <form method="post" autocomplete="off">
                         {% csrf_token %}
                           <h2>Registro</h2>
                    <input type="text" id='in_text' placeholder="Introduce tu usuario" name='us'><br>
                    <input type="email" id='in_text' placeholder="Introduce tu correo electronico" name='email'><br>
                    <input type="text" id='in_text' placeholder="Introduce tu nombre real" name='nombre'><br>
                    <input type="password" id='in_text' placeholder="Introduce tu contraseña" name='pw'><br>
                    <input type="password" id='in_text' placeholder="Vuelve a introducir tu contraseña" name='pw2'><br>
                    <button type="submit">Registrarme</button>
                           <p>¿Quizas quieras leer nuestros terminos y condiciones antes de empezar? <a href='{% url 'cms:terminos' %}'>Terminos y condiciones  Zinemas</a></p>
                    <h3>¿Ya tienes una cuenta? <a href='{% url 'cms:login' %}'>Iniciar sesión</a></h3>
                  </form>
                       </div>
              </div>

{% endblock %}